### ISSUE TITLE
Usage for mono and stereo files?

### ISSUE THREAD

**Issue by max8599** [gabrielwolf/audiocut#1]
Hello Gabriel, my problem is that i need to make chunks with different length-sizes but i don't wanna lose important signal information from the original wav-file, which is always in stereo. 
So is your chunk code designed for mono wav-files or also can i also use it for my stereo wav-files?

**Comment by gabrielwolf** [comment]
Hi max8599,
sorry for the delay. Stereo is supported. Different chuck lengths unfortunately not.
Best, Gabriel
